name: PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Flutter test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test
